name: A workflow for my Hello World life
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          REGISTRY_URL: docker.pkg.github.com
          IMAGE_NAME: omer
        run: |
            docker build -t "${{ IMAGE_NAME }}" .
            docker run "${{ IMAGE_NAME }}"
