name: A workflow for my Hello World life 
on: push
jobs:
        build:
                name: Hello world action
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v1
                        - env:
                                IMAGE_NAME: omer
                        run:
                                docker build -t ${{ IMAGE_NAME }} .
