name: A workflow for my Hello World life
on: push
env:
  IMAGE_NAME: omer
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
          run:
            docker build -t ${{ IMAGE_NAME }} .
