name: A workflow for my Hello World life
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          REGISTRY_URL: om
          IMAGE_NAME: "${{ env.REGISTRY_URL }}er"
        run: |
            docker build -t "${IMAGE_NAME}" .
            docker run "${IMAGE_NAME}"
