name: A workflow for my Hello World life 
on: push
jobs:
        build:
                name: Hello world action
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v1
                        - env:
                                FILE_PATH: docker.pkg.github.com
                        run:
                                docker build -f ${{ FILE_PATH }} .
